# Generated by Django 5.1.14 on 2025-11-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('choices', models.JSONField()),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
