# Generated by Django 5.1.14 on 2025-11-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizaplikacja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizaplikacja.question')),
            ],
        ),
    ]
